### ISSUE TITLE
error while build packages

### ISSUE THREAD

**Issue by jiban-jyoti** [yangliu28/swarm_robot_ros_sim#5]
I am getting error while building packages. I am using ROS kinetic.

![Screenshot from 2019-06-12 16-40-13](https://user-images.githubusercontent.com/44982306/59346884-f3d0ba00-8d30-11e9-96c3-36c0389a7775.png)

**Comment by yangliu28** [comment]
Package `swarm_robot_msgs` is not properly built, I have nothing to give as to why, without any info about your OS, ROS version, gazebo version, the command you have executed.

For this problem, a simple search for the error message should do the trick. Many errors are likely not related to the source code but environment setup.

**Comment by aleua-mehani** [comment]
hey !!
thank you for sharing this great work .
I'm getting the same error , I'm using Ros melodic in Ubuntu 18.04 .
could you help me please , thank you.

**Comment by GrantDare** [comment]
I get this issue too. The error is that the custom messages are not generated. I am not sure how to do this using catkin_simple either. Kinetic 16.04

**Comment by CodeFatherG** [comment]
I have created a pr #6 that solved this issue for me

**Comment by aleua-mehani** [comment]
Thank you very much for your help , i Added <build_depend> tags to packages swarm_robot_description and swarm_robot_simulation , and i successfully build the package, and successfully run the simulation in ros kinetic ubuntu 16.04 , i will try it in ros melodic and give you a feedback 
thank you.

**Comment by CodeFatherG** [comment]
Hi @yangliu28, just wondering why you reverted it? Confirmed by @aleua-mehani on ROS Kinetic.

**Comment by yangliu28** [comment]
> Hi @yangliu28, just wondering why you reverted it? Confirmed by @aleua-mehani on ROS Kinetic.

Hi @ThePapaG, the revert was a mistake click. I didn't commit the revert, so the PR went through. Thanks for your effort.

**Comment by aleua-mehani** [comment]
Actually , Add <build_depend> tags solve the build issues in both ROS kinetic and melodic but when i run the simulation just the line and aggregation formation work , the dispersion  formation fails !!its shows that error :
terminate called after throwing an instance of 'std::runtime_error'
  what():  Time is out of dual 32-bit range
Aborted (core dumped)
